### PR TITLE
Enable SSO for XDMOD and coldfront

### PR DESCRIPTION
**Pull request by treydock**
This uses latest ondemand-dex build that supports sessions and also latest OnDemand that allows adding new redirect URIs to default OnDemand client entry.

### CODE REVIEW

**Comment by aebruno** [comment]
Not sure how much we care, but logging out no longer works. You can logout out of Coldfront but when you click login, you're logged back in as the same user (Due to the sticky Dex session). Same with OOD. Looks like a logout endpoint [may not be supported in Dex yet](https://github.com/dexidp/dex/issues/1697). This may pose an issue for those who want to show off different roles in their application.

**Comment by dsajdak** [comment]
It's not ideal for the ColdFront part of the demo to not be able to login/logout multiple times as different users.  However, there are work arounds if this is not possible to get working in our current setup.  It may be a little confusing to the participants.

**Comment by plessbd** [comment]
I was thinking have them use a Private browser and non Private browser.
The non private browser will be the "main" one and then the private will be for switching users.

Though we do have to think about how this will effect each others tutorials as well.

We might want to have them clear their cookies for localhost between parts.

**Comment by aebruno** [comment]
To support logging out in Coldfront we added back LDAP authentication in #42

**Pull request merged**
