### PR TITLE
xdmod9.0-rc3

### PR DESCRIPTION
**Pull request by plessbd**
updated version of xdmod

### CODE REVIEW

**Comment by plessbd** [comment]
this is not related to the rpm
I am guessing you didnt do a fresh install so the certificates got rebuilt or something
run `/srv/xdmod/scripts/xdmod-setup-sso.sh` to have it pull in the correct cert is my guess

**Comment by aebruno** [comment]
I re-ran `/srv/xdmod/scripts/xdmod-setup-sso.sh` and still no luck. The certs have not changed. Anything else that could be missing?

**Comment by aebruno** [comment]
Just a guess but perhaps it's related to this: https://github.com/ubccr/simplesamlphp-module-authoidcoauth2/commit/b434189743099c976ab1cd084d92d880d9075b2d

**Comment by plessbd** [comment]
updated to not verify ssl when doing curl requests

**Pull request merged**
